<!DOCTYPE html>
<html>
    <head>
        <title> ${solution.name} - Teszt Feladat</title>
    </head>
    <body>
    <h1>Teszt Feladat</h1>
    <p>
        <a href="${solution.urlRepo}">Megoldás</a>
    </p>
    <p>A feladat elkészítőjének adatai</p>
    <table border="1px solid black">
        <tr>
            <td>Név</td>
            <td>${solution.name}</td>
        </tr>
        <tr>
            <td>Elérhetőség</td>
            <td>${solution.email}</td>
        </tr>
    </table>
    <a href="http://lpsolutions.hu">L&P Solutions</a>
    </body>
</html>